import { ProductType } from '@/enums';
import { type Product } from '@/interfaces';

export const PRODUCT_LIST_01: Product[] = [
  {
    id: 1,
    name: 'Apple Watch Ultra',
    description: 'Titanium Case Orange Loop',
    descriptionLong: '',
    price: 637.672,
    type: ProductType.new,
    sku: '1234567',
    discount: 0,
    photos: ['/images/products/product-01.png'],
  },
  {
    id: 2,
    name: 'iPhone 14 Pro',
    description: 'Color Deep Purple 128GB',
    descriptionLong:
      'El iPhone 14 Pro Deep Purple es un teléfono inteligente de última generación con un diseño elegante y sofisticado. Cuenta con una pantalla Super Retina XDR de 6.7 pulgadas y un potente chip A16 Bionic para un rendimiento excepcional. Su cámara triple de 12 megapíxeles captura imágenes de calidad profesional y ofrece funciones de seguridad como el reconocimiento facial Face ID. Con resistencia al agua y al polvo IP68, es un dispositivo confiable en todas las situaciones. Además, su cuerpo de vidrio y metal brinda una sensación premium en la mano.',
    price: 1949.862,
    type: ProductType.sale,
    sku: '1234567',
    discount: 40,
    photos: [
      '/images/products/product-02.png',
      '/images/products/product-02.png',
      '/images/products/product-02.png',
      '/images/products/product-02.png',
      '/images/products/product-02.png',
    ],
  },
  {
    id: 3,
    name: 'iPhone 14 Pro',
    description: 'Color Gold 128GB',
    descriptionLong: '',
    price: 1049.862,
    type: ProductType.default,
    sku: '1234567',
    discount: 0,
    photos: ['/images/products/product-03.png'],
  },
  {
    id: 4,
    name: 'Galaxy Z Flip4',
    description: 'Color Bora Purple 128GB',
    descriptionLong: '',
    price: 797.09,
    type: ProductType.default,
    sku: '1234567',
    discount: 0,
    photos: ['/images/products/product-04.png'],
  },
  {
    id: 5,
    name: 'iPhone 14 Pro Max',
    description: 'Color Gold 128GB',
    descriptionLong: '',
    price: 1800.862,
    type: ProductType.default,
    sku: '1234567',
    discount: 0,
    photos: ['/images/products/product-05.png'],
  },
  {
    id: 6,
    name: 'iPhone 14 Pro Max',
    description: 'Color Deep Purple 128GB',
    descriptionLong: '',
    price: 1800.862,
    type: ProductType.default,
    sku: '1234567',
    discount: 0,
    photos: ['/images/products/product-06.png'],
  },
];

export const PRODUCT_LIST_02: Product[] = [
  {
    id: 7,
    name: 'Apple MacBook Air 13”',
    description: 'Chip M1 CPU 8GB RAM',
    descriptionLong: '',
    price: 1139.99,
    type: ProductType.sale,
    sku: '1234567',
    discount: 40,
    photos: ['/images/products/product-07.png'],
  },
  {
    id: 8,
    name: 'Apple iPad 10.2”',
    description: '9ªGen WiFi 64 GB Color Silver',
    descriptionLong: '',
    price: 419.99,
    type: ProductType.sale,
    sku: '1234567',
    discount: 40,
    photos: ['/images/products/product-08.png'],
  },
  {
    id: 9,
    name: 'HP Gamer Victus',
    description: '16-D0500LA Intel Core i5',
    descriptionLong: '',
    price: 699.99,
    type: ProductType.new,
    sku: '1234567',
    discount: 0,
    photos: ['/images/products/product-09.png'],
  },
  {
    id: 10,
    name: 'Lenovo Ideapad 1',
    description: 'Intel Celeron 4GB RAM',
    descriptionLong: '',
    price: 299.99,
    type: ProductType.new,
    sku: '1234567',
    discount: 0,
    photos: ['/images/products/product-10.png'],
  },
  {
    id: 11,
    name: 'Lenovo Convertible Flex1',
    description: '5i Intel Core I3 8GB RAM',
    descriptionLong: '',
    price: 497.09,
    type: ProductType.default,
    sku: '1234567',
    discount: 0,
    photos: ['/images/products/product-11.png'],
  },
  {
    id: 12,
    name: 'ASUS Laptop 15,6”',
    description: 'Intel Core i3 12GB RAM',
    descriptionLong: '',
    price: 1449.862,
    type: ProductType.default,
    sku: '1234567',
    discount: 0,
    photos: ['/images/products/product-12.png'],
  },
];

export const PRODUCT_LIST_03: Product[] = [
  {
    id: 13,
    name: 'Lavadora FENSA 21kg',
    description: 'Premium Care Pro 21 X Silver',
    descriptionLong: '',
    price: 449.99,
    type: ProductType.sale,
    sku: '1234567',
    discount: 40,
    photos: ['/images/products/product-13.png'],
  },
  {
    id: 14,
    name: 'Lavadora LG 12kg',
    description: 'Carga frontal',
    descriptionLong: '',
    price: 499.99,
    type: ProductType.sale,
    sku: '1234567',
    discount: 40,
    photos: ['/images/products/product-14.png'],
  },
  {
    id: 15,
    name: 'Side by Side LG 598',
    description: 'LS66SXTC InstaView Craft',
    descriptionLong: '',
    price: 1889.99,
    type: ProductType.new,
    sku: '1234567',
    discount: 0,
    photos: ['/images/products/product-15.png'],
  },
  {
    id: 16,
    name: 'Refrigerador Samsung',
    description: 'No Frost 234 lt Top Mount',
    descriptionLong: '',
    price: 509.99,
    type: ProductType.default,
    sku: '1234567',
    discount: 0,
    photos: ['/images/products/product-16.png'],
  },
  {
    id: 17,
    name: 'Microondas 25lt Wurden',
    description: 'WMW-WONDER25',
    descriptionLong: '',
    price: 69.99,
    type: ProductType.default,
    sku: '1234567',
    discount: 0,
    photos: ['/images/products/product-17.png'],
  },
  {
    id: 18,
    name: 'Microondas 20 lt Galanz',
    description: 'GLC0ZV20S5SB071',
    descriptionLong: '',
    price: 34.99,
    type: ProductType.default,
    sku: '1234567',
    discount: 0,
    photos: ['/images/products/product-18.png'],
  },
];
