import '../styles/index.scss';
import 'swiper/css';
import 'swiper/css/effect-coverflow';
import 'swiper/css/pagination';
import 'swiper/css/bundle';

import { Inter } from 'next/font/google';
import localFont from 'next/font/local';

import { Footer, Header } from '@/elements/organisms';

const inter = Inter({ subsets: ['latin'] });
const phonk = localFont({
  src: '../../public/fonts/phonk.woff2',
  display: 'swap',
  variable: '--font-phonk',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} ${phonk.variable}`}>
        <Header />
        <div className='pt-22 xl:pt-32'>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
